# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8897f834a79a4d423831a7e06e2f016335da131e40d41480ef40b15fd7c0b2f79c60d2e29d86368ad32c4c5f53180b979849c006b1afe4474243b0cd95e8b93

test:
  secret_key_base: e555690b20928f53b81eef0da2b36c6840d52de5fed4be2a56381190f6f5b31e21331fe354a5c86172de2b2876273746dbfd85b7e8ce506fedc83a25883271ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
